spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hebe
    username: root
    password: koreait
    driver-class-name: org.mariadb.jdbc.Driver

mybatis:
  mapper-locations: mybatis-mapper/**/*.xml
  type-aliases-package: com.hebe